### ISSUE TITLE
Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

### ISSUE THREAD

**Issue by ekdnam** [microsoft/chat-copilot#111]
**Describe the bug**
I am trying to run the project with my AzureOpenAI credentials. However, it leads the the error

```
Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
```

I have already created the deployment on AzureOpenAI, it is up and running.

**To Reproduce**
1. start up the server and frontend with `dotnet run` and `yarn start`

**Expected behavior**
The chatbot should return a response.

**Screenshots**
This is the error trace
```
Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:37240'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:40443
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/ekdnam/Projects/copilot-chat-app/webapi
info: SemanticKernel.Service.Program[0]
      Health probe: https://localhost:40443/healthz
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/messageRelayHub - -
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/healthz - -
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:40443/healthz - - - 200 - text/plain 13.6845ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/messageRelayHub - -
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:40443/messageRelayHub - - - 101 - - 714.8757ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 OPTIONS https://localhost:40443/chatSession/getAllChats/4cd0f668-8aa0-46f8-99f5-bbd098cd0494.b5a078fe-4334-4ee6-9122-352bf41674ec - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 OPTIONS https://localhost:40443/chatSession/getAllChats/4cd0f668-8aa0-46f8-99f5-bbd098cd0494.b5a078fe-4334-4ee6-9122-352bf41674ec - - - 204 - - 1.7864ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/chatSession/getAllChats/4cd0f668-8aa0-46f8-99f5-bbd098cd0494.b5a078fe-4334-4ee6-9122-352bf41674ec application/json -
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:40443/chatSession/getAllChats/4cd0f668-8aa0-46f8-99f5-bbd098cd0494.b5a078fe-4334-4ee6-9122-352bf41674ec application/json - - 200 - application/json;+charset=utf-8 39.2631ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 OPTIONS https://localhost:40443/chatSession/create - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 OPTIONS https://localhost:40443/chatSession/create - - - 204 - - 0.6206ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:40443/chatSession/create application/json 127
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST https://localhost:40443/chatSession/create application/json 127 - 201 - application/json;+charset=utf-8 38.1543ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 OPTIONS https://localhost:40443/chatSession/getChatMessages/73d94922-f2be-43a8-b3ed-769fc4f96add?startIdx=0&count=1 - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 OPTIONS https://localhost:40443/chatSession/getChatMessages/73d94922-f2be-43a8-b3ed-769fc4f96add?startIdx=0&count=1 - - - 204 - - 0.2834ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/chatSession/getChatMessages/73d94922-f2be-43a8-b3ed-769fc4f96add?startIdx=0&count=1 application/json -
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:40443/chatSession/getChatMessages/73d94922-f2be-43a8-b3ed-769fc4f96add?startIdx=0&count=1 application/json - - 200 - application/json;+charset=utf-8 19.2040ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 OPTIONS https://localhost:40443/speechToken - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 OPTIONS https://localhost:40443/speechToken - - - 204 - - 0.1704ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 OPTIONS https://localhost:40443/speechToken - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 OPTIONS https://localhost:40443/speechToken - - - 204 - - 0.0550ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/speechToken application/json -
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:40443/speechToken application/json - - 200 - application/json;+charset=utf-8 5.7146ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/speechToken application/json -
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET https://localhost:40443/speechToken application/json - - 200 - application/json;+charset=utf-8 0.2466ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 OPTIONS https://localhost:40443/chat - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 OPTIONS https://localhost:40443/chat - - - 204 - - 0.4357ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST https://localhost:40443/chat application/json 270
info: SemanticKernel.Service.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
fail: Microsoft.SemanticKernel.IKernel[0]
      Something went wrong while rendering the semantic function or while executing the text completion. Function: ChatSkill.funcf7c0625a835e4d588e88223f37c30a42. Error: Invalid request: The request is not valid, HTTP status: 404. Details: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
      Status: 404 (Not Found)
      ErrorCode: DeploymentNotFound
      
      Content:
      {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}
      
      Headers:
      OpenAI-Processing-Ms: REDACTED
      x-ms-client-request-id: 71fb1aa3-6d1b-411c-89bc-34de587346be
      apim-request-id: REDACTED
      Strict-Transport-Security: REDACTED
      X-Content-Type-Options: REDACTED
      x-ms-region: REDACTED
      Date: Mon, 07 Aug 2023 05:07:51 GMT
      Content-Length: 198
      Content-Type: application/json
      
      Microsoft.SemanticKernel.AI.AIException: Invalid request: The request is not valid, HTTP status: 404
       ---> Azure.RequestFailedException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
      Status: 404 (Not Found)
      ErrorCode: DeploymentNotFound
      
      Content:
      {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}
      
      Headers:
      OpenAI-Processing-Ms: REDACTED
      x-ms-client-request-id: 71fb1aa3-6d1b-411c-89bc-34de587346be
      apim-request-id: REDACTED
      Strict-Transport-Security: REDACTED
      X-Content-Type-Options: REDACTED
      x-ms-region: REDACTED
      Date: Mon, 07 Aug 2023 05:07:51 GMT
      Content-Length: 198
      Content-Type: application/json
      
         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsync(ChatHistory chat, ChatRequestSettings chatSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsTextAsync(String text, CompleteRequestSettings textSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.SkillDefinition.SKFunction.<>c__DisplayClass19_0.<<FromSemanticConfig>g__LocalFunc|1>d.MoveNext()
fail: Microsoft.SemanticKernel.IKernel[0]
      Invalid request: The request is not valid, HTTP status: 404: Microsoft.SemanticKernel.AI.AIException: Invalid request: The request is not valid, HTTP status: 404
       ---> Azure.RequestFailedException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
      Status: 404 (Not Found)
      ErrorCode: DeploymentNotFound
      
      Content:
      {"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}
      
      Headers:
      OpenAI-Processing-Ms: REDACTED
      x-ms-client-request-id: 71fb1aa3-6d1b-411c-89bc-34de587346be
      apim-request-id: REDACTED
      Strict-Transport-Security: REDACTED
      X-Content-Type-Options: REDACTED
      x-ms-region: REDACTED
      Date: Mon, 07 Aug 2023 05:07:51 GMT
      Content-Length: 198
      Content-Type: application/json
      
         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsync(ChatHistory chat, ChatRequestSettings chatSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsTextAsync(String text, CompleteRequestSettings textSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.SkillDefinition.SKFunction.<>c__DisplayClass19_0.<<FromSemanticConfig>g__LocalFunc|1>d.MoveNext()
fail: Microsoft.SemanticKernel.IKernel[0]
      Function call fail during pipeline step 0: ChatSkill.Chat. Error: Invalid request: The request is not valid, HTTP status: 404
Hello, world!
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST https://localhost:40443/chat application/json 270 - 400 - text/plain;+charset=utf-8 2070.9510ms

```

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language:C#
 - Source: main branch of the repo

**Additional context**

**Comment by alliscode** [comment]
Hi @ekdnam, thank you for creating this issue. Would you please double check if you have the two required models deployed to your AzureOpenAI instance:

- gpt-35-turbo
- text-embedding-ada-002

- > **IMPORTANT:** For `AzureOpenAI`, if you deployed models `gpt-35-turbo` and `text-embedding-ada-002` with custom names (instead of each own's given name), also use the parameters:

        ```powershell
        -CompletionModel {DEPLOYMENT_NAME} -EmbeddingModel {DEPLOYMENT_NAME} -PlannerModel {DEPLOYMENT_NAME}
        ```

**Comment by ekdnam** [comment]
@alliscode I had forgotten to deploy embeddings to AzureOpenAI. I was able to solve that error. Thanks!
However, I got a new error - please find the trace below
```
fail: Microsoft.SemanticKernel.IKernel[0]
      Something went wrong while executing the native function. Function: <GetDelegateInfo>b__0. Error: Service error: The service failed to process the request, HTTP status:500
      Microsoft.SemanticKernel.AI.AIException: Service error: The service failed to process the request, HTTP status:500
       ---> Azure.RequestFailedException: Service request failed.
      Status: 500 (Internal Server Error)
      
      Content:
      { "statusCode": 500, "message": "Internal server error", "activityId": "04ac5880-7bfb-4987-96e8-4b18d67a8f36" }
      
      Headers:
      x-ms-client-request-id: 22cdc27b-42dc-434d-b261-d4b990a1c56e
      apim-request-id: REDACTED
      Strict-Transport-Security: REDACTED
      X-Content-Type-Options: REDACTED
      x-ms-region: REDACTED
      Date: Tue, 08 Aug 2023 05:27:42 GMT
      Content-Length: 111
      Content-Type: application/json
      
         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetEmbeddingsAsync(String deploymentOrModelName, EmbeddingsOptions embeddingsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetEmbeddingsAsync(IList`1 data, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.GenerateEmbeddingAsync[TValue,TEmbedding](IEmbeddingGeneration`2 generator, TValue value, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SearchAsync(String collection, String query, Int32 limit, Double minRelevanceScore, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SearchAsync(String collection, String query, Int32 limit, Double minRelevanceScore, Boolean withEmbeddings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at SemanticKernel.Service.CopilotChat.Skills.ChatSkills.SemanticChatMemorySkill.QueryMemoriesAsync(String query, String chatId, Int32 tokenLimit, ISemanticTextMemory textMemory) in /Users/ekdnam/Projects/copilot-chat-app/webapi/CopilotChat/Skills/ChatSkills/SemanticChatMemorySkill.cs:line 57
         at SemanticKernel.Service.CopilotChat.Skills.ChatSkills.SemanticChatMemorySkill.QueryMemoriesAsync(String query, String chatId, Int32 tokenLimit, ISemanticTextMemory textMemory) in /Users/ekdnam/Projects/copilot-chat-app/webapi/CopilotChat/Skills/ChatSkills/SemanticChatMemorySkill.cs:line 57
         at SemanticKernel.Service.CopilotChat.Skills.ChatSkills.ChatSkill.GetChatResponseAsync(String chatId, SKContext chatContext) in /Users/ekdnam/Projects/copilot-chat-app/webapi/CopilotChat/Skills/ChatSkills/ChatSkill.cs:line 341
         at SemanticKernel.Service.CopilotChat.Skills.ChatSkills.ChatSkill.ChatAsync(String message, String userId, String userName, String chatId, String messageType, String planJson, String messageId, SKContext context) in /Users/ekdnam/Projects/copilot-chat-app/webapi/CopilotChat/Skills/ChatSkills/ChatSkill.cs:line 267
         at Microsoft.SemanticKernel.SkillDefinition.SKFunction.InvokeAsync(SKContext context, CompleteRequestSettings settings)
fail: Microsoft.SemanticKernel.IKernel[0]
      Function call fail during pipeline step 0: ChatSkill.Chat. Error: Service error: The service failed to process the request, HTTP status:500
Hello, world!
```

Does this mean I _have_ to use a query vector store? Nothing in-memory?

**Comment by alliscode** [comment]
@ekdnam is this error persistent? Generally, 500 level errors are indicating a transient error within the service itself and are considered retriable.  If the issue is persistent you might want to configure logging in your Azure OpenAI instance to get more information about what is going wrong.

As for the vector store, the default setup is to use `volatile` (in memory), but this can be configured in the `MemoryStore` section of the `appsettings.json` file within the `webapi`.

**Comment by alliscode** [comment]
@ekdnam We've verified that Azure OpenAI experienced intermittent outage yesterday. Can you confirm if you are still experiencing this 500 error?

**Comment by ekdnam** [comment]
@alliscode thanks for letting me know. 

The app is working now.

**Comment by ekdnam** [comment]
Thanks for your help! I am closing the issue now.
