### ISSUE TITLE
Error after upgrading NuGet packages - MissingMethodException

### ISSUE THREAD

**Issue by ransht** [microsoft/chat-copilot#1174]
**Title**: Error after upgrading NuGet packages - MissingMethodException in AzureOpenAIClientOptions

**Description**:
After upgrading all NuGet packages to their latest versions in the `chat-copilot` project, I encountered the following error at runtime:

```
## Error ##
* Message:  Method not found: 'Void Azure.AI.OpenAI.AzureOpenAIClientOptions.set_ApplicationId(System.String)'.
* Type:     MissingMethodException [System.MissingMethodException]
* Location: at Microsoft.KernelMemory.AI.AzureOpenAI.Internals.AzureOpenAIClientBuilder.Build(AzureOpenAIConfig config, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.KernelMemory.AI.AzureOpenAI.AzureOpenAITextEmbeddingGenerator..ctor(AzureOpenAIConfig config, ITextTokenizer textTokenizer, ILoggerFactory loggerFactory, HttpClient httpClient)
   at Microsoft.KernelMemory.DependencyInjection.<>c__DisplayClass0_0.<AddAzureOpenAIEmbeddingGeneration>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.KernelMemory.KernelMemoryBuilder.ReuseRetrievalEmbeddingGeneratorIfNecessary(IServiceProvider serviceProvider)
   at Microsoft.KernelMemory.KernelMemoryBuilder.BuildServerlessClient()
## Unhandled exception. System.MissingMethodException: Method not found: 'Void Azure.AI.OpenAI.AzureOpenAIClientOptions.set_ApplicationId(System.String)'.
   at Microsoft.KernelMemory.AI.AzureOpenAI.Internals.AzureOpenAIClientBuilder.Build(AzureOpenAIConfig config, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.KernelMemory.AI.AzureOpenAI.AzureOpenAITextEmbeddingGenerator..ctor(AzureOpenAIConfig config, ITextTokenizer textTokenizer, ILoggerFactory loggerFactory, HttpClient httpClient)
   at Microsoft.KernelMemory.DependencyInjection.<>c__DisplayClass0_0.<AddAzureOpenAIEmbeddingGeneration>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.KernelMemory.KernelMemoryBuilder.ReuseRetrievalEmbeddingGeneratorIfNecessary(IServiceProvider serviceProvider)
   at Microsoft.KernelMemory.KernelMemoryBuilder.BuildServerlessClient()
   at Microsoft.KernelMemory.KernelMemoryBuilder.Build()
```

### Steps to reproduce:
1. Upgrade all NuGet packages to their latest versions.
2. Run the application.

### Expected behavior:
The application should start and work as expected after upgrading NuGet packages.

### Actual behavior:
The application crashes at startup with a `System.MissingMethodException` indicating that the method `Azure.AI.OpenAI.AzureOpenAIClientOptions.set_ApplicationId` is missing.

### Additional details:
- The issue seems related to a version mismatch between `Azure.AI.OpenAI` and other related libraries (like `Microsoft.KernelMemory` or `Microsoft.Extensions.DependencyInjection`).
- I’m using .NET 8.0.

Please let me know if additional information is needed. Thank you!

**Comment by dluc** [comment]
Fixed :-)
