### ISSUE TITLE
Getting 500s from Azure.AI.OpenAI.OpenAIClient.GetEmbeddingsAsync

### ISSUE THREAD

**Issue by wasker** [microsoft/chat-copilot#123]
**Describe the bug**

I'm trying to chat with the bot locally, however, this doesn't go anywhere and in web API logs I'm seeing a lot of errors that look like below. How do I debug this?

fail: SemanticKernel.Service.CopilotChat.Skills.ChatSkills.ChatSkill[0]
      Cannot search collection f375dd31-e341-4ab0-a2c6-dc5087cb3aa6-LongTermMemory
      Microsoft.SemanticKernel.AI.AIException: Service error: The service failed to process the request, HTTP status:500
       ---> Azure.RequestFailedException: Internal server error
      Status: 500 (Internal Server Error)

      Content:
      { "statusCode": 500, "message": "Internal server error", "activityId": "19ccf22c-8e3d-4a93-8eb9-028cef52fd3a" }

      Headers:
      x-ms-client-request-id: 29beecdc-e4bc-4929-b5be-28594a1db6e1
      apim-request-id: REDACTED
      Strict-Transport-Security: REDACTED
      X-Content-Type-Options: REDACTED
      x-ms-region: REDACTED
      Date: Tue, 08 Aug 2023 00:13:25 GMT
      Content-Length: 111
      Content-Type: application/json

         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetEmbeddingsAsync(String deploymentOrModelName, EmbeddingsOptions embeddingsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetEmbeddingsAsync(IList`1 data, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.GenerateEmbeddingAsync[TValue,TEmbedding](IEmbeddingGeneration`2 generator, TValue value, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SearchAsync(String collection, String query, Int32 limit, Double minRelevanceScore, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()

or

fail: SemanticKernel.Service.CopilotChat.Skills.ChatSkills.ChatSkill[0]
      Cannot search collection f375dd31-e341-4ab0-a2c6-dc5087cb3aa6-WorkingMemory
      Microsoft.SemanticKernel.AI.AIException: Service error: The service failed to process the request, HTTP status:500
       ---> Azure.RequestFailedException: Internal server error
      Status: 500 (Internal Server Error)

      Content:
      { "statusCode": 500, "message": "Internal server error", "activityId": "95f34a4a-c52c-4121-a0e5-d58ab0d6a6e3" }

      Headers:
      x-ms-client-request-id: 8647cf4a-e191-4fa7-8480-b58c37977d0b
      apim-request-id: REDACTED
      Strict-Transport-Security: REDACTED
      X-Content-Type-Options: REDACTED
      x-ms-region: REDACTED
      Date: Tue, 08 Aug 2023 00:12:21 GMT
      Content-Length: 111
      Content-Type: application/json

**To Reproduce**

1. Completed local devbox setup.
2. Started the app.
3. Typing questions and not getting responses reliably.

**Expected behavior**

Get responses reliably.

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: main branch of the repo.

**Comment by crickman** [comment]
@wasker Azure OpenAI experienced intermittent outage yesterday.  Can you confirm if you are still experiencing this 500 error?

**Comment by wasker** [comment]
Yeah, I think it's better today. It's unfortunate that there's no visibility into what's going on, the AOAI doesn't have a way to look up those correlation IDs.

**Comment by crickman** [comment]
Thank you for the confirmation and feedback.
