### ISSUE TITLE
Getting exception when retrieving records from volatile memory

### ISSUE THREAD

**Issue by ashishwebt** [microsoft/chat-copilot#125]
**Describe the bug**
Hi Im getting folwing error in Chat Copilot app with volatile memory on line 81 in webapi\CopilotChat\Skills\ChatSkills\DocumentMemorySkill.cs file.
inner exception is:

**To Reproduce**
1. Register a plugin.
2. Ask a question that plugin solves
3. Ask another question.'

**Expected behavior**
Retrieve similar records from volatile memory.

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/120636885/b4cb471c-47fe-41ba-8ca9-26f6ff279b8c)

**Platform**
 - OS: [Windows]
 - IDE: [Visual Studio 2022]
 - Language: [C#]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**
InnerException    {"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.\r\nStatus: 404 (Not Found)\r\nErrorCode: DeploymentNotFound\r\n\r\nContent:\r\n{"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}\r\n\r\nHeaders:\r\nOpenAI-Processing-Ms: REDACTED\r\nx-ms-client-request-id: 1652580f-151c-46c0-a75b-bc71e7b8a4b5\r\napim-request-id: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nx-ms-region: REDACTED\r\nDate: Tue, 08 Aug 2023 09:19:46 GMT\r\nContent-Length: 198\r\nContent-Type: application/json\r\n"}    System.Exception {Azure.RequestFailedException}

Stack trace:
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.<RunRequestAsync>d__25`1.MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.<InternalGetEmbeddingsAsync>d__14.MoveNext()
   at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.<GenerateEmbeddingAsync>d__0`2.MoveNext()
   at Microsoft.SemanticKernel.Memory.SemanticTextMemory.<SearchAsync>d__7.MoveNext()
   at Microsoft.SemanticKernel.Memory.SemanticTextMemory.<SearchAsync>d__7.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at SemanticKernel.Service.CopilotChat.Skills.ChatSkills.DocumentMemorySkill.<QueryDocumentsAsync>d__4.MoveNext() in C:\Work\chat-copilot-main\webapi\CopilotChat\Skills\ChatSkills\DocumentMemorySkill.cs:line 81

**Comment by ashishwebt** [comment]
@alliscode I was using model name instead of deployment name for text embedding model. Sorry for being dumdum! :D
