### ISSUE TITLE
Unable to generate bot response. Details: Error: 400: => Unknown error (UnknownError): Something went wrong: Retry failed after 2 tries. (The proxy tunnel request to proxy failed with status code '503'.")

### ISSUE THREAD

**Issue by dasheffie** [microsoft/chat-copilot#313]
**Describe the bug**
When submitting a prompt in Chat Copilot, I get an error that the "proxy tunnel request to proxy failed with status code '503'." However, I have no problem connecting to Azure OpenAI outside of Chat Copliot using the same proxy.

**To Reproduce**
1. Clone chat-copilot repo
2. `cd .\scripts\`
3. `.\Install.ps1`
4. `.\Configure.ps1 -AIService AzureOpenAI -APIKey 57c623ef...r32re139 -Endpoint https://oai-we2re-...openai.azure.com/ -CompletionModel ai-gpt35turbo-...-dev -EmbeddingModel ai-txtada002...-dev -PlannerModel ai-gpt35turbo-...-dev`
5. `.\Start.ps1`
6. Open a new Powershell window
7. `cd .\webapi\`
8. `dotnet run`
9. Type "What is democracy?" and hit `Enter`
10. See error

**Expected behavior**
Receive a response from Azure OpenAI completion model

**Screenshots and Attachments**
error message in UI:
![image](https://github.com/microsoft/chat-copilot/assets/104397289/5384234d-e425-4743-9bcd-dbe2cf7a6d51)
webapp runtime log:
![image](https://github.com/microsoft/chat-copilot/assets/104397289/3a613ea4-cfb1-472d-98af-57458592a2b4)
webapi runtime log:

```Text
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\...> cd "C:\Users\...\chat-copilot\webapi\"
PS C:\Users\...\chat-copilot\webapi> dotnet run
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:40443
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\...\chat-copilot\webapi
info: CopilotChat.WebApi.Program[0]
      Health probe: https://localhost:40443/healthz
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:40443/healthz - -
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:40443/healthz - - - 200 - text/plain 37.0695ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:40443/serviceOptions - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:40443/chatSession/getAllChats/c05c61eb-65e4-4223-915a-fe72b0c9ece1 - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:40443/contentSafety/status - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 OPTIONS https://localhost:40443/serviceOptions - - - 204 - - 4.7037ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 OPTIONS https://localhost:40443/contentSafety/status - - - 204 - - 4.7487ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 OPTIONS https://localhost:40443/chatSession/getAllChats/c05c61eb-65e4-4223-915a-fe72b0c9ece1 - - - 204 - - 4.7802ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:40443/chatSession/getAllChats/c05c61eb-65e4-4223-915a-fe72b0c9ece1 application/json -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:40443/contentSafety/status application/json -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:40443/serviceOptions application/json -
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:40443/contentSafety/status application/json - - 200 - application/json;+charset=utf-8 37.9686ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:40443/serviceOptions application/json - - 200 - application/json;+charset=utf-8 42.6195ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:40443/chatSession/getAllChats/c05c61eb-65e4-4223-915a-fe72b0c9ece1 application/json - - 200 - application/json;+charset=utf-8 48.5077ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:40443/chatSession/create - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 OPTIONS https://localhost:40443/chatSession/create - - - 204 - - 0.1293ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:40443/chatSession/create application/json 42
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET https://localhost:40443/messageRelayHub - -
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:40443/chatSession/create application/json 42 - 201 - application/json;+charset=utf-8 60.5347ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:40443/speechToken - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:40443/speechToken - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 OPTIONS https://localhost:40443/speechToken - - - 204 - - 0.1620ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 OPTIONS https://localhost:40443/speechToken - - - 204 - - 0.1643ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:40443/speechToken application/json -
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:40443/speechToken application/json - - 200 - application/json;+charset=utf-8 10.5019ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:40443/speechToken application/json -
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:40443/speechToken application/json - - 200 - application/json;+charset=utf-8 0.5876ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 OPTIONS https://localhost:40443/chat - -
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 OPTIONS https://localhost:40443/chat - - - 204 - - 0.2187ms
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 POST https://localhost:40443/chat application/json 142
info: CopilotChat.WebApi.Auth.PassThroughAuthenticationHandler[0]
      Allowing request to pass through
info: Microsoft.SemanticKernel.IKernel[0]
      Action: GetCompletionsAsync. Azure OpenAI Deployment Name: ai-gpt35zzzzz-zzzzzzz-zzzzz-dev.
warn: Microsoft.SemanticKernel.IKernel[0]
      Error executing action [attempt 1 of 1]. Reason: System.Net.Http.HttpRequestException. Will retry after 2000ms
fail: Microsoft.SemanticKernel.IKernel[0]
      Error executing request, max retry count reached. Reason: System.Net.Http.HttpRequestException
      System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
warn: Microsoft.SemanticKernel.IKernel[0]
      Error executing action [attempt 1 of 1]. Reason: System.Net.Http.HttpRequestException. Will retry after 2000ms
fail: Microsoft.SemanticKernel.IKernel[0]
      Error executing request, max retry count reached. Reason: System.Net.Http.HttpRequestException
      System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
fail: Microsoft.SemanticKernel.IKernel[0]
      Something went wrong while rendering the semantic function or while executing the text completion. Function: ChatSkill.funcae42eab4566e45988b6aa45cea5fecad. Error: Unknown error (UnknownError): Something went wrong: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.") (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."). Details: (null)
      Microsoft.SemanticKernel.AI.AIException: Unknown error (UnknownError): Something went wrong: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.") (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.")
       ---> System.AggregateException: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.") (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.")
       ---> Azure.RequestFailedException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
       ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         --- End of inner exception stack trace ---
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
         at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         --- End of inner exception stack trace ---
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
       ---> (Inner Exception #1) Azure.RequestFailedException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
       ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         --- End of inner exception stack trace ---
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
         at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)<---

         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsync(ChatHistory chat, ChatRequestSettings chatSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsTextAsync(String text, CompleteRequestSettings textSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.SkillDefinition.SKFunction.<>c__DisplayClass19_0.<<FromSemanticConfig>g__LocalFunc|1>d.MoveNext()
fail: Microsoft.SemanticKernel.IKernel[0]
      Something went wrong while executing the native function. Function: <GetDelegateInfo>b__0. Error: Unknown error (UnknownError): Something went wrong: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.") (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.")
      Microsoft.SemanticKernel.AI.AIException: Unknown error (UnknownError): Something went wrong: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.") (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.")
       ---> System.AggregateException: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.") (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.")
       ---> Azure.RequestFailedException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
       ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         --- End of inner exception stack trace ---
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
         at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         --- End of inner exception stack trace ---
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
       ---> (Inner Exception #1) Azure.RequestFailedException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
       ---> System.Net.Http.HttpRequestException: The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'."
         at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         --- End of inner exception stack trace ---
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
         at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)<---

         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsync(ChatHistory chat, ChatRequestSettings chatSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsTextAsync(String text, CompleteRequestSettings textSettings, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.SkillDefinition.SKFunction.<>c__DisplayClass19_0.<<FromSemanticConfig>g__LocalFunc|1>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.SemanticKernel.SkillDefinition.SKFunction.InvokeAsync(SKContext context, CompleteRequestSettings settings, CancellationToken cancellationToken)
         at CopilotChat.WebApi.Skills.ChatSkills.ChatSkill.ExtractAudienceAsync(SKContext context) in C:\Users\...\chat-copilot\webapi\Skills\ChatSkills\ChatSkill.cs:line 195
         at CopilotChat.WebApi.Skills.ChatSkills.ChatSkill.GetAudienceAsync(SKContext context) in C:\Users\...\chat-copilot\webapi\Skills\ChatSkills\ChatSkill.cs:line 471
         at CopilotChat.WebApi.Skills.ChatSkills.ChatSkill.GetChatResponseAsync(String chatId, String userId, SKContext chatContext, CancellationToken cancellationToken) in C:\Users\...\chat-copilot\webapi\Skills\ChatSkills\ChatSkill.cs:line 337
         at CopilotChat.WebApi.Skills.ChatSkills.ChatSkill.ChatAsync(String message, String userId, String userName, String chatId, String messageType, String planJson, String messageId, SKContext context, CancellationToken cancellationToken) in C:\Users\...\chat-copilot\webapi\Skills\ChatSkills\ChatSkill.cs:line 307
         at Microsoft.SemanticKernel.SkillDefinition.SKFunction.InvokeAsync(SKContext context, CompleteRequestSettings settings, CancellationToken cancellationToken)
fail: Microsoft.SemanticKernel.IKernel[0]
      Function call fail during pipeline step 0: ChatSkill.Chat. Error: Unknown error (UnknownError): Something went wrong: Retry failed after 2 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.") (The proxy tunnel request to proxy 'https://proxy...com:912/' failed with status code '503'.")
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:40443/chat application/json 142 - 400 - text/plain;+charset=utf-8 5421.6378ms
```

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: https://github.com/microsoft/chat-copilot.git cloned 2023-09-07

**Additional context**

**Comment by dasheffie** [comment]
I was able to get around the issue by deploying Chat Copilot using docker compose. Still not sure what the issue is when I try to deploy it in Windows. But, I used all the same Azure OpenAI configuration values in appsettings.json as I used in my .env file when using docker compose.

**Comment by dasheffie** [comment]
The solution was to remove the proxy settings altogether. Every internal application I have built requires proxy settings when communicating over the internet. But, apparently, not for our Azure OpenAI API.
