### ISSUE TITLE
import Document with tesseract OCR enabled on M2 Mac arm64 is giving DllNotFoundException for libleptonica-1.82.0.dylib

### ISSUE THREAD

**Issue by gotoashishgupta** [microsoft/chat-copilot#352]
**Describe the bug**
 Uploading pdf documents for long term memory under Documents tab fails on M2 Macbook pro arm64 platform with following error:
 ```
 fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
       ---> System.DllNotFoundException: Failed to find library "libleptonica-1.82.0.dylib" for platform x64.
         at InteropDotNet.LibraryLoader.LoadLibrary(String fileName, String platformName)
         at InteropRuntimeImplementer.LeptonicaApiSignaturesInstance.LeptonicaApiSignaturesImplementation..ctor(LibraryLoader loader)
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         --- End of inner exception stack trace ---
         at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
         at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
         at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
         at InteropDotNet.InteropRuntimeImplementer.CreateInstance[T]()
         at Tesseract.Interop.LeptonicaApi.Initialize()
         at Tesseract.Interop.TessApi.Initialize()
         at Tesseract.Interop.TessApi.get_Native()
         at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode, IEnumerable`1 configFiles, IDictionary`2 initialOptions, Boolean setOnlyNonDebugVariables)
         at Tesseract.TesseractEngine..ctor(String datapath, String language, EngineMode engineMode)
         at CopilotChat.WebApi.Extensions.CopilotChatServiceExtensions.<>c__DisplayClass4_0.<AddPersistentOcrSupport>b__1(IServiceProvider sp) in /Users/ag568e/personal/mlcode/chat-copilot/webapi/Extensions/ServiceExtensions.cs:line 137
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
         at lambda_method84(Closure, IServiceProvider, Object[])
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
 
 ```

**To Reproduce**
1. Go to 'Documents' tab
2. Click on 'upload' button and Select a pdf file to upload
3. The upload fails
4. See error logs in terminal

**Expected behavior**
A document upload should work without error

**Screenshots**
<img width="1441" alt="Screenshot 2023-09-16 at 2 17 11 PM" src="https://github.com/microsoft/chat-copilot/assets/1331478/0051db45-2e26-4284-b49b-64d1e3c8add4">

**Platform**
 - OS: [Mac M2 chipset arm64 platform]
 - Source: [Tesseract Initialization]

**Additional context**

**Comment by teresaqhoang** [comment]
Self-assigning to test on MAC. Will add more details after testing

**Comment by teresaqhoang** [comment]
Hey @gotoashishgupta, this is an issue with tesseract in Linux / MacOS, where its native dependencies (libleptonica in this case) aren't included for any platforms other than Windows, so you have to manually compile and link the library within the Chat Copilot webapi. 

You can try installing `libleptonica-dev`, copying the *.so file to `webapi/bin/Debug/net6.0/x64` folder, and renaming it to `leptonica-1.82.0.dll`.

I found these threads most helpful in providing guidance: 
- https://stackoverflow.com/questions/69813484/error-could-not-load-file-or-assembly-tesseract-on-ubuntu-using-net-core-3-1/71066165#71066165
- https://github.com/sirfz/tesserocr/issues/268

Closing this thread as this issue is related to Leptonica Library. As the library is a third-party library, it is out of the scope for further support in this forum. Please continue with the thread linked above!

**Comment by gotoashishgupta** [comment]
@teresaqhoang `leptonica-1.82.0.dll` is already present at `webapi/bin/Debug/net6.0/x64`, however I still see the bug

**Comment by kimvdm** [comment]
@gotoashishgupta Did you find a solution to this problem? I'm currently experiencing the same issue.

**Comment by lucas-fsousa** [comment]
this is a little strange. In .NET 8 when I run the console application through visual studio, everything works fine, but if I run the .exe file directly, I get the error "Exception has been thrown by the target of an invocation. ## Failed to find library " leptonica-1.82.0.dll" for platform x64."

There is the x86 and x64 folder with the appropriate DLLS, but I still get the error. I even tried moving the dlls to the system32 context, but the error remains. 

When we compile the application, the x86 and x64 folder is also copied to the program root as shown in the image below, but the API cannot be loaded, as the system does not identify the existence of the DLL

![image](https://github.com/microsoft/chat-copilot/assets/66752018/e146ae2c-de99-4b68-82da-05510d6081a2)
![image](https://github.com/microsoft/chat-copilot/assets/66752018/bbb4b619-39d7-4341-9154-bd44eab515f2)

**Comment by namdo21917** [comment]
Did anyone have a solution for this? I'm facing the same problem on MacOS Intel.

**Comment by lucas-fsousa** [comment]
I solved this at the time for windows. If it helps, this is the link to the solution.
,
https://stackoverflow.com/questions/78105308/leptonica-1-82-0-not-found-in-net-runtime

**Comment by kimvdm** [comment]
> Did anyone have a solution for this? I'm facing the same problem like Lucas on MacOS Intel.

https://github.com/charlesw/tesseract/blob/master/docs/Get%20running%20on%20macOS.md

If you use an Apple silicon chip the homebrew path isn’t /usr/local but /opt/homebrew. Also for me it asked for 1.82.0 for libleptonica instead of 1.80.0 and version 5.0 (50) instead of 4.1 which is used here for tesseract.

**Comment by Dadams2** [comment]
Hey I managed to get things working with homebrew on apple silicon by adding the following to my csproj:

```xml
  <Target Name="link_deps" AfterTargets="AfterBuild">
  <Exec Command="ln -sf /opt/homebrew/lib/libleptonica.dylib $(OutDir)x64/libleptonica-1.82.0.dylib"/>
  <Exec Command="ln -sf /opt/homebrew/lib/libtesseract.dylib $(OutDir)x64/libtesseract50.dylib"/>
  </Target>
```

It would appear there have been some naming convention changes since the docs were written.

**Comment by 1mBC** [comment]
> Hey I managed to get things working with homebrew on apple silicon by adding the following to my csproj:
> 
>   <Target Name="link_deps" AfterTargets="AfterBuild">
>   <Exec Command="ln -sf /opt/homebrew/lib/libleptonica.dylib $(OutDir)x64/libleptonica-1.82.0.dylib"/>
>   <Exec Command="ln -sf /opt/homebrew/lib/libtesseract.dylib $(OutDir)x64/libtesseract50.dylib"/>
>   </Target>
> It would appear there have been some naming convention changes since the docs were written.

This instantly saved me. Thanks a lot.

**Comment by guinavarro** [comment]
> Hey I managed to get things working with homebrew on apple silicon by adding the following to my csproj:
> 
>   <Target Name="link_deps" AfterTargets="AfterBuild">
>   <Exec Command="ln -sf /opt/homebrew/lib/libleptonica.dylib $(OutDir)x64/libleptonica-1.82.0.dylib"/>
>   <Exec Command="ln -sf /opt/homebrew/lib/libtesseract.dylib $(OutDir)x64/libtesseract50.dylib"/>
>   </Target>
> It would appear there have been some naming convention changes since the docs were written.

This solved my problem, thanks! Mac Air m1

**Comment by danyukezz** [comment]
> Hey I managed to get things working with homebrew on apple silicon by adding the following to my csproj:
> 
>   <Target Name="link_deps" AfterTargets="AfterBuild">
>   <Exec Command="ln -sf /opt/homebrew/lib/libleptonica.dylib $(OutDir)x64/libleptonica-1.82.0.dylib"/>
>   <Exec Command="ln -sf /opt/homebrew/lib/libtesseract.dylib $(OutDir)x64/libtesseract50.dylib"/>
>   </Target>
> It would appear there have been some naming convention changes since the docs were written.

bro is a life saver, thanks!!!!
