### ISSUE TITLE
WebAPI does not recognize environment variable in Azure Appservice

### ISSUE THREAD

**Issue by trungklam** [microsoft/chat-copilot#477]
**Describe the bug**
Recently, I deployed the chat-copilot webapi to Azure AppServices (The app works fine in local with dotnet secret) and use the environment variable to manage its secret. 
Basically, I have to set some of the below secret in AppServices:

`SemanticMemory__Services__AzureOpenAIText__APIKey`
`SemanticMemory__Services__AzureFormRecognizer_APIKey`
`SemanticMemory__Services__AzureOpenAIEmbedding_APIKey`

Everything works fine except the _SemanticMemory__Services__AzureOpenAIEmbedding_APIKey_, I got the below exception:

> Unhandled exception. System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'apiKey')
   at Microsoft.SemanticKernel.Diagnostics.Verify.ThrowArgumentWhiteSpaceException(String paramName)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.AzureOpenAIClientBase..ctor(String modelId, String endpoint, String apiKey, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextEmbedding.AzureTextEmbeddingGeneration..ctor(String modelId, String endpoint, String apiKey, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.SemanticMemory.DependencyInjection.&lt;&gt;c__DisplayClass0_0.&lt;AddAzureOpenAIEmbeddingGeneration&gt;b__1(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor``2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.SemanticMemory.MemoryClientBuilder.FromConfiguration(SemanticMemoryConfig config, IConfiguration servicesConfiguration)
   at Microsoft.SemanticMemory.MemoryClientBuilder.FromAppSettings(String settingsDirectory)
   at CopilotChat.WebApi.Extensions.ISemanticMemoryClientExtensions.AddSemanticMemoryServices(WebApplicationBuilder appBuilder) in D:\Projects\chat-copilot\webapi\Extensions\ISemanticMemoryClientExtensions.cs:line 56
   at CopilotChat.WebApi.Program.Main(String[] args) in D:\Projects\chat-copilot\webapi\Program.cs:line 52
   at CopilotChat.WebApi.Program.&lt;Main&gt;(String[] args)

So far the apiKey of _AzureOpenAIEmbedding_ is not recognized properly even it was set. I tried set it directly in appsettings.json and deploy again then it works - so the issue should be around somewhere when SM pass the apikey to SK connector, but I'm unable to figure out it yet. 
I'm also try to set env _AzureOpenAIEmbeddings__ApiKey_ for SK but it doesnt work neither.
Any help will be appreciated ! Thank you !

**Expected behavior**
 The app should recognize the env correctly

**Comment by TaoChenOSU** [comment]
Hi @trungklam,

Thank you for reporting the issue!

To assist you further, could you let us know how you deployed chat copilot? Did you run the script manually or use the deploy-to-azure button?

**Comment by victor-v-rad** [comment]
+1
My case is similar but for OpenAI

1. chat-copilot 0.7 version 
2. deployed infra through "Deploy to Azure" button
3. pwsh package-webapi.ps1
4. pwsh deploy-webapi.ps1 ...
5. open provided url 
6. logs:
> Unhandled exception. System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'apiKey')
   at Microsoft.SemanticKernel.Diagnostics.Verify.ThrowArgumentWhiteSpaceException(String paramName)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.OpenAIClientBase..ctor(String modelId, String apiKey, String organization, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextEmbedding.OpenAITextEmbeddingGeneration..ctor(String modelId, String apiKey, String organization, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.SemanticMemory.DependencyInjection.<>c__DisplayClass2_0.<AddOpenAITextEmbeddingGeneration>b__0(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.SemanticMemory.MemoryClientBuilder.FromConfiguration(SemanticMemoryConfig config, IConfiguration servicesConfiguration)
   at Microsoft.SemanticMemory.MemoryClientBuilder.FromAppSettings(String settingsDirectory)
   at CopilotChat.WebApi.Extensions.ISemanticMemoryClientExtensions.AddSemanticMemoryServices(WebApplicationBuilder appBuilder)

**Comment by TaoChenOSU** [comment]
> +1 My case is similar but for OpenAI
> 
> 1. chat-copilot 0.7 version
> 2. deployed infra through "Deploy to Azure" button
> 3. pwsh package-webapi.ps1
> 4. pwsh deploy-webapi.ps1 ...
> 5. open provided url
> 6. logs:
> 
> > Unhandled exception. System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'apiKey')
> > at Microsoft.SemanticKernel.Diagnostics.Verify.ThrowArgumentWhiteSpaceException(String paramName)
> > at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.OpenAIClientBase..ctor(String modelId, String apiKey, String organization, HttpClient httpClient, ILoggerFactory loggerFactory)
> > at Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextEmbedding.OpenAITextEmbeddingGeneration..ctor(String modelId, String apiKey, String organization, HttpClient httpClient, ILoggerFactory loggerFactory)
> > at Microsoft.SemanticMemory.DependencyInjection.<>c__DisplayClass2_0.b__0(IServiceProvider serviceProvider)
> > at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
> > at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
> > at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
> > at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
> > at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
> > at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
> > at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
> > at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
> > at Microsoft.SemanticMemory.MemoryClientBuilder.FromConfiguration(SemanticMemoryConfig config, IConfiguration servicesConfiguration)
> > at Microsoft.SemanticMemory.MemoryClientBuilder.FromAppSettings(String settingsDirectory)
> > at CopilotChat.WebApi.Extensions.ISemanticMemoryClientExtensions.AddSemanticMemoryServices(WebApplicationBuilder appBuilder)

Hello @victor-v-rad,

If you go to your WebApi instance and look for you app settings, do you find the following settings?
1. SemanticMemory:TextGeneratorType (what is the value of this setting?)
2. SemanticMemory:Services:OpenAI:APIKey

![image](https://github.com/microsoft/chat-copilot/assets/12570346/46ba601d-4b7a-43b5-a3ec-04fa1320f883)

**Comment by victor-v-rad** [comment]
<img width="831" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/7c6de64e-ca9a-4a5b-8518-72b779b4bb2b">

_____________________

<img width="903" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/9f104588-0617-4225-a8b6-98a3e738cf12">

_____________________

<img width="893" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/faf03434-0ce9-4ff8-af6f-06cfb310adc9">
_____________________

<img width="785" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/a4959123-9f8d-449b-98c6-11a27b4591f2">
_____________________

<img width="929" alt="image" src="https://github.com/microsoft/chat-copilot/assets/106504/411d06d6-2fe9-4804-8632-bd1eb4d49f29">

**Comment by trungklam** [comment]
Hi @TaoChenOSU , sorry for my late response, I was a bit fully occupied last week.
I did a debug session into the Semantic Memory and turn out it was a grammar mistake
`SemanticMemory__Services__AzureFormRecognizer_APIKey`
`SemanticMemory__Services__AzureOpenAIEmbedding_APIKey`
It was missing an "_" before the APIKey, the correct one should be
`SemanticMemory__Services__AzureFormRecognizer__APIKey`
`SemanticMemory__Services__AzureOpenAIEmbedding__APIKey`

I have no other objective for this issue, so you can process with closing it. Thanks a lot
