### ISSUE TITLE
SemanticMemory with Qdrant error

### ISSUE THREAD

**Issue by geffzhang** [microsoft/chat-copilot#547]
SemanticMemory error：

warn: Microsoft.SemanticMemory.MemoryStorage.Qdrant.Client.QdrantClient[0]
      Qdrant responded with error: NotFound, {"status":{"error":"Not found: Collection `chatmemory` doesn't exist!"},"time":7.2e-6}
fail: Microsoft.SemanticMemory.MemoryStorage.Qdrant.Client.QdrantClient[0]
      GetSimilarListAsync failed: Response status code does not indicate success: 404 (Not Found)., {"status":{"error":"Not found: Collection `chatmemory` doesn't exist!"},"time":7.2e-6}
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.SemanticMemory.MemoryStorage.Qdrant.Client.QdrantClient`1.ValidateResponse(HttpResponseMessage response, String content, String methodName)
fail: WebAPI.Skills.ChatSkills.ChatSkill[0]
      Unexpected failure searching chatmemory
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at Microsoft.SemanticMemory.MemoryStorage.Qdrant.Client.QdrantClient`1.ValidateResponse(HttpResponseMessage response, String content, String methodName)
         at Microsoft.SemanticMemory.MemoryStorage.Qdrant.Client.QdrantClient`1.GetSimilarListAsync(String collectionName, Embedding target, Double minSimilarityScore, Int32 limit, Boolean withVectors, IEnumerable`1 requiredTags, CancellationToken cancellationToken)
         at Microsoft.SemanticMemory.MemoryStorage.Qdrant.QdrantMemory.GetSimilarListAsync(String indexName, Embedding embedding, Int32 limit, Double minRelevanceScore, ICollection`1 filters, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
         at Microsoft.SemanticMemory.MemoryStorage.Qdrant.QdrantMemory.GetSimilarListAsync(String indexName, Embedding embedding, Int32 limit, Double minRelevanceScore, ICollection`1 filters, Boolean withEmbeddings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at Microsoft.SemanticMemory.Search.SearchClient.SearchAsync(String index, String query, Double minRelevanceScore, ICollection`1 filters, Int32 limit, CancellationToken cancellationToken)
         at Microsoft.SemanticMemory.Search.SearchClient.SearchAsync(String index, String query, Double minRelevanceScore, ICollection`1 filters, Int32 limit, CancellationToken cancellationToken)

**Comment by crickman** [comment]
Thank you for reporting this.

**Comment by geffzhang** [comment]
https://github.com/microsoft/chat-copilot/issues/512

**Comment by evchaki** [comment]
@geffzhang - it looks like the PR has been entered.  Please try this again.
