### ISSUE TITLE
Invalid memory store type: Disk

### ISSUE THREAD

**Issue by rvermeire** [microsoft/chat-copilot#562]
**Describe the bug**
At startup there is an error message in the UI "Invalid memory store type: Disk". MemoryStoreType Disk does indeed not exist while it is configured to use Disk

```
Error getting service options. Details: Error: 500: System.ArgumentException: 
Invalid memory store type: Disk at CopilotChat.WebApi.Options.MemoryStoreTypeExtensions.GetMemoryStoreType(SemanticMemoryConfig memoryOptions, IConfiguration configuration) in 
C:\Users\Ronald\repo\sk\chat-copilot\webapi\Options\MemoryStoreType.cs:line 73 at CopilotChat.WebApi.Controllers.ServiceInfoController.GetServiceInfo() in 
C:\Users\Ronald\repo\sk\chat-copilot\webapi\Controllers\ServiceInfoController.cs:line 62 at lambda_method36(Closure, Object, Object[]) 
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments) 
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.
InvokeActionMethodAsync() at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& stat...
```

https://github.com/microsoft/chat-copilot/tree/main/memorypipeline/appsettings.json

```
      "SimpleVectorDb": {
        "StorageType": "Disk",
        "Directory": "../tmp/database"
      },
```

**To Reproduce**
Configure the SimpleVectorDb StorageType as Disk and Start up the webclient. Message appears above the chat input field. 

**Expected behavior**
No error message and be able to use Disk or change the config in appsettings.json so SimpleVectorDb uses Volatile as StorageType all the time and change the documentation/comment that Disk is not available.

**Platform**
Windows
Latest available version (10/31)

**Comment by crickman** [comment]
Thanks for report this issue.

**Comment by raj-microsoft** [comment]
I'm seeing the same error.

![image](https://github.com/microsoft/chat-copilot/assets/93758959/0d20334f-30b9-45d4-9a41-d162edd95e57)

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: Invalid memory store type: Disk
         at CopilotChat.WebApi.Options.MemoryStoreTypeExtensions.GetMemoryStoreType(SemanticMemoryConfig memoryOptions, IConfiguration configuration) in C:\Repos\chat-copilot\webapi\Options\MemoryStoreType.cs:line 73
         at CopilotChat.WebApi.Controllers.ServiceInfoController.GetServiceInfo() in C:\Repos\chat-copilot\webapi\Controllers\ServiceInfoController.cs:line 62
         at lambda_method36(Closure, Object, Object[])
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at CopilotChat.WebApi.Services.MaintenanceMiddleware.Invoke(HttpContext ctx, IKernel kernel) in C:\Repos\chat-copilot\webapi\Services\MaintenanceMiddleware.cs:line 59
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by Woland2k** [comment]
Same error with latest version.

**Comment by crickman** [comment]
Thanks, I have a cycle to address this now.  Appreciate the follow-up.

**Comment by luko0610** [comment]
I assume this is due to this in MemoryStoreType.cs:

```var simpleVectorDbConfig = memoryOptions.GetServiceConfig<SimpleVectorDbConfig>(configuration, "SimpleVectorDb");
            if (simpleVectorDbConfig != null)
            {
                type = simpleVectorDbConfig.StorageType.ToString();
                if (type.Equals("Volatile", StringComparison.OrdinalIgnoreCase))
                {
                    return MemoryStoreType.Volatile;
                }
                else if (type.Equals("TextFile", StringComparison.OrdinalIgnoreCase))
                {
                    return MemoryStoreType.TextFile;
                }
            }
```

I could create a pull request to adapt the type equals check here.

**Comment by fragilities** [comment]
I still have the same error, running on mac

**Comment by BasalGanglia** [comment]
I can make a hack like this to make the error go away, but not quite sure if I broke something else ;) it seems it does write them to the text file 

`
                type = simpleVectorDbConfig.StorageType.ToString();
                if (type.Equals("Disk", StringComparison.OrdinalIgnoreCase))
                {
                    type = "TextFile";
                }
`

**Comment by crickman** [comment]
Anyone can change the setting value to "TextFile" in the appsettings.json if that unblocks them.

There is an updated version of semantic-memory, so I'm just in the process of triangulating with that update.
