### ISSUE TITLE
The latest version 607 is inaccessible after deployment

### ISSUE THREAD

**Issue by howard2019007** [microsoft/chat-copilot#625]
The latest version 607 is inaccessible after deploying Azure and is running fine on-premises
![image](https://github.com/microsoft/chat-copilot/assets/49265228/b789aab4-d3da-437a-8511-2d5454c94fb1)
![image](https://github.com/microsoft/chat-copilot/assets/49265228/00a272c7-09af-497b-be10-ce8b2f5af096)

**Comment by howard2019007** [comment]
I found that I had to redeploy my Azure resources in order to use the updated project normally, and I couldn't initiate access after the project was deployed

**Comment by momuno** [comment]
Hi @howard2019007, could you please clarify what you mean by "version 607"?

**Comment by glahaye** [comment]
@howard2019007 Are you saying that UPGRADING caused you to see a 500.30 error but that DEPLOYING FROM SCRATCH worked for you?

**Comment by howard2019007** [comment]
Deploying from scratch worked for me, but since I was bound my own domain name, deploying from scratch would cause the binding to fail and would need to be re-bound

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Gil ***@***.***>
发送时间: 2023年11月21日 7:46
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [microsoft/chat-copilot] The latest version 607 is inaccessible after deployment (Issue #625)


@howard2019007<https://github.com/howard2019007> Are you saying that UPGRADING caused you to see a 500.30 error but that DEPLOYING FROM SCRATCH worked for you?

―

**Comment by momuno** [comment]
In order to reproduce the error, can you please clarify what you mean by "version 607" ?  Or, could you please provide the commit hash you are using?  Thank you.

**Comment by howard2019007** [comment]
This issue is present with all recent releases

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by threegitty350** [comment]
I'm also experiencing this issue since SK beta 6 - 8. It is giving an error relating to a storage index (azure). 
**BlobBaseClient.DownloadContent**
BlobNotFound
```
   at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions validationOptions, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, DownloadTransferValidationOptions transferValidationOverride, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)

```

I have cloned Build #642 and loading it in visual studio i immediately was prompted with a debug error:


**File:**
ISemanticMemoryClientExtensions.cs > Line 57

IKernelMemory memory = memoryBuilder.FromAppSettings().Build();

_(I'm not sure if it is related to the error that is returned in Azure. I hope this information was helpful)_

```Exception has occurred: CLR/System.ArgumentException
An exception of type 'System.ArgumentException' occurred in Microsoft.SemanticKernel.Connectors.AI.OpenAI.dll but was not handled in user code: 'The value cannot be an empty string or composed entirely of whitespace.'
   at Microsoft.SemanticKernel.Diagnostics.Verify.ThrowArgumentWhiteSpaceException(String paramName)
   at Microsoft.SemanticKernel.Diagnostics.Verify.NotNullOrWhiteSpace(String str, String paramName)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.AzureOpenAIClientBase..ctor(String deploymentName, String endpoint, String apiKey, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextEmbedding.AzureOpenAITextEmbeddingGeneration..ctor(String deploymentName, String endpoint, String apiKey, String modelId, HttpClient httpClient, ILoggerFactory loggerFactory)
   at Microsoft.KernelMemory.DependencyInjection.<>c__DisplayClass0_0.<AddAzureOpenAIEmbeddingGeneration>b__1(IServiceProvider serviceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.KernelMemory.KernelMemoryBuilder.FromConfiguration(KernelMemoryConfig config, IConfiguration servicesConfiguration)
   at Microsoft.KernelMemory.KernelMemoryBuilder.FromAppSettings(String settingsDirectory)
   at CopilotChat.WebApi.Extensions.ISemanticMemoryClientExtensions.AddSemanticMemoryServices(WebApplicationBuilder appBuilder) in C:\Users\<redacted>\chat-copilot\webapi\Extensions\ISemanticMemoryClientExtensions.cs:line 57
   at CopilotChat.WebApi.Program.<Main>d__0.MoveNext() in C:\Users\<redacted>\chat-copilot\webapi\Program.cs:line 53```

**Comment by glahaye** [comment]
@threegitty350 Actually, your stack trace is helpful.

If I understand correctly, what is happening is that an older version of Chat Copilot was deployed and then a newer one was deployed in the same resource group.

There have been many breaking changes over the past few months, including to configuration settings.

In order to reflect the new configuration settings properly, you need to run the latest version of ..\chat-copilot\scripts\deploy\deploy-azure.ps1

Have you done that?

Running that script will NOT be destructive to your current resources and will simply add the missing resources and configurations settings.

**Comment by howard2019007** [comment]
> @threegitty350 Actually, your stack trace is helpful.
> 
> If I understand correctly, what is happening is that an older version of Chat Copilot was deployed and then a newer one was deployed in the same resource group.
> 
> There have been many breaking changes over the past few months, including to configuration settings.
> 
> In order to reflect the new configuration settings properly, you need to run the latest version of ..\chat-copilot\scripts\deploy\deploy-azure.ps1
> 
> Have you done that?
> 
> Running that script will NOT be destructive to your current resources and will simply add the missing resources and configurations settings.

I ran ./deploy-azure.ps1 -Subscription xxxxxx -DeploymentName comlan -AIService AzureOpenAI -AIApiKey xxxxxx -AIEndpoint https://xxxxxx.openai.azure.com/ -BackendClientId xxxxxx - FrontendClientId xxxxxxx -TenantId xxxxxxx -Region eastus but it doesn't work

**Comment by glahaye** [comment]
What I have found so far is that the deploy-azure script doesn't seem to update existing configurations for the Chat Copilot app service.  Looking into this more.

**Comment by glahaye** [comment]
@howard2019007 It looks like this problem is solve with #672 

If you want, you can verify that this works for you.
