### ISSUE TITLE
App stuck on looking for backend

### ISSUE THREAD

**Issue by Henson87** [microsoft/chat-copilot#650]
**Describe the bug**
After following the steps to install the app fails to find the backend on start up. No additional changes have been made. The backend is up and running at https://localhost:40443. No auth was configured either. The console shows a syntax error. 

![image](https://github.com/microsoft/chat-copilot/assets/70236759/9e979109-412a-4135-988b-4eb0d5b14051)

**To Reproduce**
Follow the main instructions install steps 
![image](https://github.com/microsoft/chat-copilot/assets/70236759/0590cfa6-e57b-447e-b00e-3b699ad9ab91)

The backend is up and running 
![image](https://github.com/microsoft/chat-copilot/assets/70236759/87007b31-5eb6-44bc-b149-6f52f8fab014)

**Expected behavior**
I expected it to work out of the box when running it locally. 

**Platform**
 - OS: Windows 10 
 - IDE: VS Code
 - Powershell Version: 7.2.16

Any help on troubleshooting the issue would be appreciated.

**Comment by Henson87** [comment]
Looking into this more, I found an error on start up, not sure if it's associated with the app being stuck on looking for backend. 

`fail: CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService[0]
      Error migrating chat memories
      Microsoft.SemanticKernel.Diagnostics.HttpOperationException: Requests to the Embeddings_Create Operation under Azure OpenAI API version 2023-09-01-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 10 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit.
      Status: 429 (Too Many Requests)
      ErrorCode: 429

      Content:
      {"error":{"code":"429","message": "Requests to the Embeddings_Create Operation under Azure OpenAI API version 2023-09-01-preview have exceeded call rate limit of your current OpenAI S0 pricing tier. Please retry after 10 seconds. Please go here: https://aka.ms/oai/quotaincrease if you would like to further increase the default rate limit."}}

         at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetEmbeddingsAsync(String deploymentOrModelName, EmbeddingsOptions embeddingsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
         at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetEmbeddingsAsync(IList`1 data, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.GenerateEmbeddingAsync[TValue,TEmbedding](IEmbeddingGeneration`2 generator, TValue value, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SaveInformationAsync(String collection, String text, String id, String description, String additionalMetadata, CancellationToken cancellationToken)
         at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.<>c__DisplayClass9_0.<<InternalMigrateAsync>g__SetTokenMemory|2>d.MoveNext() in C:\Users\john.a.henson\source\repos\chat-copilot\webapi\Services\MemoryMigration\ChatMemoryMigrationService.cs:line 136
      --- End of stack trace from previous location ---
         at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.InternalMigrateAsync(CancellationToken cancellationToken) in C:\Users\john.a.henson\source\repos\chat-copilot\webapi\Services\MemoryMigration\ChatMemoryMigrationService.cs:line 96
         at CopilotChat.WebApi.Services.MemoryMigration.ChatMemoryMigrationService.MigrateAsync(CancellationToken cancellationToken) in C:\Users\john.a.henson\source\repos\chat-copilot\webapi\Services\MemoryMigration\ChatMemoryMigrationService.cs:line 57`

**Comment by Henson87** [comment]
Hi @threegitty350 thanks for your response. I have verified the healthz

![image](https://github.com/microsoft/chat-copilot/assets/70236759/1509f4b9-9540-48f2-9f8c-f4853521b795)

I deleted all cookies but unfortunately the same result.

**Comment by Henson87** [comment]
Additionally, I have tested this on my personal machine that is a windows 11. No luck with the same result, Backend healthy with the UI unable to find the backend.

**Comment by AFenhoff** [comment]
I'm trying the deployment to Azure but running into problems there too. @threegitty350 I'm hoping you can help @Henson87 figure out the local deployment before I dig too far into the Azure deployment.

**Comment by darylbatchelor** [comment]
I had this issue too on a Windows build and was stuck for a while. Turned out that it was due to not configuring the correct deployment names of models as per the Step 3. Configure Chat Copilot. Specifically **-CompletionModel {DEPLOYMENT_NAME} -EmbeddingModel {DEPLOYMENT_NAME} -PlannerModel {DEPLOYMENT_NAME}**. I can't speak for OpenAI endpoints, but it you are using Azure OpenAI you need to log into your azure service and find the deployment names of your models.  

If you are like me you may have not named them the same as the actual model names.  Once I ran the .\Configure.ps1 script again with the correct completion, embedding and planner deployment names it worked no worries.  I suggest that maybe some better error handling needs to be implemented to catch this as it seems to be a common issue and the current error handling was not obvious. 

Hope this helps!

**Comment by crickman** [comment]
@Henson87 - Curious, what is the name you are using for your embedding model? (I'd expect it to be 'text-embedding-ada-002' while the completion and planner models would be a 'gpt' variant.)

**Comment by crickman** [comment]
Resolved by increasing token limit for embedding model after verifying configuration.
