### ISSUE TITLE
Unexpected failure searching chatmemory

### ISSUE THREAD

**Issue by Rsimk** [microsoft/chat-copilot#716]
chat copilot generates answer, but then it generates error message in the log:

fail: CopilotChat.WebApi.Skills.ChatSkills.ChatSkill[0]
      Unexpected failure searching chatmemory
      System.TypeLoadException: Could not load type 'Azure.Search.Documents.Models.SearchQueryVector' from assembly 'Azure.Search.Documents, Version=11.5.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'.
         at Microsoft.SemanticMemory.MemoryStorage.AzureCognitiveSearch.AzureCognitiveSearchMemory.GetSimilarListAsync(String indexName, Embedding embedding, Int32 limit, Double minRelevanceScore, ICollection`1 filters, Boolean withEmbeddings, CancellationToken cancellationToken)+MoveNext()
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Microsoft.SemanticMemory.MemoryStorage.AzureCognitiveSearch.AzureCognitiveSearchMemory.GetSimilarListAsync(String indexName, Embedding embedding, Int32 limit, Double minRelevanceScore, ICollection`1 filters, Boolean withEmbeddings, CancellationToken cancellationToken)+System.IAsyncDisposable.DisposeAsync()
         at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.Enumerator.DisposeAsync()
         at Microsoft.SemanticMemory.Search.SearchClient.SearchAsync(String index, String query, Double minRelevanceScore, ICollection`1 filters, Int32 limit, CancellationToken cancellationToken)
         at CopilotChat.WebApi.Extensions.ISemanticMemoryClientExtensions.SearchMemoryAsync(ISemanticMemoryClient memoryClient, String indexName, String query, Single relevanceThreshold, Int32 resultCount, String chatId, String memoryName, CancellationToken cancellationToken) in C:\Users\rober\repo\local-openai-copilot-bot\webapi\Extensions\ISemanticMemoryClientExtensions.cs:line 96
         at CopilotChat.WebApi.Skills.ChatSkills.SemanticChatMemoryExtractor.<>c__DisplayClass0_0.<<ExtractSemanticChatMemoryAsync>g__CreateMemoryAsync|1>d.MoveNext() in C:\repo\chat-copilot\webapi\Skills\ChatSkills\SemanticChatMemoryExtractor.cs:line 112

chat-copilot is configured with Azure Cognitive Search as vector DB.

**Comment by crickman** [comment]
Thank you for reporting this.  Will investgiate and repro.

**Comment by glahaye** [comment]
This should be resolved with latest version.
