### ISSUE TITLE
Cannot read properties of undefined (reading 'getLogger')

### ISSUE THREAD

**Issue by mrugeles** [microsoft/chat-copilot#989]
**Describe the bug**
The webapp in macos has issues running,

**To Reproduce**
1. ./start.sh

**Expected behavior**
The following error appears in the browser

Uncaught runtime errors:
ERROR
Cannot read properties of undefined (reading 'getLogger')
TypeError: Cannot read properties of undefined (reading 'getLogger')
    at http://localhost:3000/static/js/bundle.js:203651:21
    at mountMemo (http://localhost:3000/static/js/bundle.js:152517:23)
    at Object.useMemo (http://localhost:3000/static/js/bundle.js:152902:20)
    at useMemo (http://localhost:3000/static/js/bundle.js:168700:25)
    at MsalProvider (http://localhost:3000/static/js/bundle.js:203650:64)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:151745:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:155029:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:156325:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:141341:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:141385:20)
**Screenshots**
![Screenshot 2024-05-24 at 2 09 37 PM](https://github.com/microsoft/chat-copilot/assets/211676/13985e7e-39f8-43d9-8d73-ac9dea5cb69e)

**Platform**
 - OS: Macos

**Comment by JasonHaley** [comment]
I just noticed this too. Seems to be due to a change last week in index.tsx. If I change the isAuthAAD if block to extend to line 63 (instead of stopping at 50) it seems to work without configuring AAD. I will want to do the AAD auth, but wanted to start learning it without first.

Here is the change I made locally:
![image](https://github.com/microsoft/chat-copilot/assets/4291604/d908e114-47c1-40fe-b468-9a8487c8aa7e)

**Comment by mrugeles** [comment]
Hi @JasonHaley that actually works. Thanks

**Comment by revilhui** [comment]
thanks~

**Comment by guymerin** [comment]
Thanks @JasonHaley that worked

**Comment by glahaye** [comment]
Fixed with #994
